import type { Tool, ToolId, Category } from './types';

export const tools: Tool[] = [
  {
    id: 'scan',
    name: 'Scan to PDF',
    description: 'Your camera. A clearer document.',
    category: 'Convert',
    icon: 'ScanLine',
    accent: 'mint',
    multiple: true,
    detail:
      'Scan documents, receipts, photos, whiteboards and ID cards with your camera. Correct edges and perspective, clean up shadows, arrange pages and download a black-and-white or color PDF. Your scans stay on your device.',
    action: 'Download PDF',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    description: 'Make the changes you need.',
    category: 'Edit & sign',
    icon: 'FilePenLine',
    accent: 'coral',
    detail:
      'Edit existing text, add text and images, highlight, draw, and add links. Your original file stays untouched.',
    action: 'Download PDF',
    editor: true,
  },
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'A few files. One neat PDF.',
    category: 'Organize',
    icon: 'Combine',
    accent: 'blue',
    detail:
      'Combine PDF files in the order you choose. Move pages between files before downloading.',
    action: 'Merge files',
    multiple: true,
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Keep just the parts you need.',
    category: 'Organize',
    icon: 'Scissors',
    accent: 'yellow',
    detail: 'Save every page separately, split every few pages, or create PDFs from custom ranges.',
    action: 'Split PDF',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Lighter files, easier sharing.',
    category: 'Convert',
    icon: 'Minimize2',
    accent: 'mint',
    detail:
      'Create a smaller PDF by turning pages into optimized images. Text will no longer be selectable; forms and links are flattened. Keep the original if you need them.',
    action: 'Compress PDF',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Your signature, without a printer.',
    category: 'Edit & sign',
    icon: 'Signature',
    accent: 'lavender',
    detail:
      'Draw your signature or upload an image and remove its paper background, then place it on the page. This is a visual signature, not a certificate-based digital signature.',
    action: 'Download signed PDF',
    editor: true,
  },
  {
    id: 'fill',
    name: 'Fill PDF forms',
    description: 'Fill it in. Send it on.',
    category: 'Edit & sign',
    icon: 'ListTodo',
    accent: 'blue',
    detail:
      'Complete existing text fields, checkboxes and choices. For a flat form, place text and marks anywhere on the page.',
    action: 'Download filled PDF',
    editor: true,
  },
  {
    id: 'organize',
    name: 'Organize pages',
    description: 'Get everything in the right order.',
    category: 'Organize',
    icon: 'LayoutGrid',
    accent: 'lavender',
    detail:
      'Reorder, rotate, duplicate and remove pages. Use the arrows or drag a page into its new position.',
    action: 'Save page order',
    multiple: true,
  },
  {
    id: 'extract',
    name: 'Extract pages',
    description: 'Make a PDF from selected pages.',
    category: 'Organize',
    icon: 'Copy',
    accent: 'mint',
    detail: 'Enter the pages you want to keep, in your preferred order. For example: 1, 3-5, 8.',
    action: 'Extract pages',
  },
  {
    id: 'delete',
    name: 'Delete pages',
    description: 'Lose the pages you don’t need.',
    category: 'Organize',
    icon: 'FileX2',
    accent: 'coral',
    detail: 'Enter the pages to remove. The remaining pages are saved in a new PDF.',
    action: 'Delete selected pages',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Put your pages the right way up.',
    category: 'Organize',
    icon: 'RotateCw',
    accent: 'yellow',
    detail: 'Rotate individual pages, or rotate the whole document with one click.',
    action: 'Save rotations',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Photos and scans, together.',
    category: 'Convert',
    icon: 'Images',
    accent: 'yellow',
    detail:
      'Turn JPG, PNG or WebP images into a PDF. Reorder your images and choose the page size.',
    action: 'Create PDF',
    multiple: true,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to images',
    description: 'Every page, a picture.',
    category: 'Convert',
    icon: 'ImageDown',
    accent: 'blue',
    detail: 'Export selected pages as high-quality JPG or PNG images, together in a ZIP file.',
    action: 'Export images',
  },
  {
    id: 'text',
    name: 'PDF to text',
    description: 'Get the words out of a PDF.',
    category: 'Convert',
    icon: 'TextSelect',
    accent: 'mint',
    detail:
      'Extract selectable text into a plain-text file. Image-only scans do not contain text to extract; this tool does not perform OCR.',
    action: 'Extract text',
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    description: 'Make it yours, on every page.',
    category: 'Edit & sign',
    icon: 'Stamp',
    accent: 'lavender',
    detail:
      'Add your own text watermark to selected pages. Choose the size, color, placement and opacity.',
    action: 'Add watermark',
  },
  {
    id: 'page-numbers',
    name: 'Page numbers',
    description: 'A little order goes a long way.',
    category: 'Edit & sign',
    icon: 'ListOrdered',
    accent: 'yellow',
    detail: 'Number selected pages at the top or bottom. Choose the starting number and text size.',
    action: 'Add page numbers',
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    description: 'Trim the edges, keep the focus.',
    category: 'Edit & sign',
    icon: 'Crop',
    accent: 'blue',
    detail:
      'Trim equal margins from each edge. Cropping hides content outside the page boundary; use Redact to permanently remove sensitive content.',
    action: 'Crop pages',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    description: 'A password for your paperwork.',
    category: 'Secure',
    icon: 'LockKeyhole',
    accent: 'lavender',
    detail:
      'Encrypt your PDF with a password required to open it. Keep the password somewhere safe; Rovty never stores it.',
    action: 'Protect PDF',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove a password you know.',
    category: 'Secure',
    icon: 'LockKeyholeOpen',
    accent: 'mint',
    detail:
      'Open a protected PDF using its password, then save a copy without password protection.',
    action: 'Save unlocked PDF',
  },
  {
    id: 'redact',
    name: 'Redact PDF',
    description: 'Keep private details private.',
    category: 'Secure',
    icon: 'ScanLine',
    accent: 'coral',
    detail:
      'Mark sensitive areas and permanently remove them from the downloaded copy. Redacted exports turn all pages into images, removing original text, links, forms and metadata.',
    action: 'Apply redactions',
    editor: true,
  },
  {
    id: 'grayscale',
    name: 'Grayscale PDF',
    description: 'A simpler shade of document.',
    category: 'Convert',
    icon: 'Contrast',
    accent: 'mint',
    detail:
      'Turn pages into black-and-white grayscale images in a new PDF. This flattens selectable text, forms and links.',
    action: 'Convert to grayscale',
  },
  {
    id: 'flatten',
    name: 'Flatten PDF',
    description: 'Make filled-in forms stay put.',
    category: 'Edit & sign',
    icon: 'Layers',
    accent: 'blue',
    detail:
      'Flatten interactive form fields into page content so their values cannot be changed as form fields. This preserves the document’s selectable text.',
    action: 'Flatten forms',
  },
  {
    id: 'metadata',
    name: 'PDF metadata',
    description: 'A fresh start behind the scenes.',
    category: 'Secure',
    icon: 'FileSearch',
    accent: 'yellow',
    detail:
      'Replace the document title and author, and remove standard subject, keywords, dates and XMP metadata. This does not remove visible content, attachments or comments.',
    action: 'Save metadata',
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    description: 'Give a troublesome PDF a chance.',
    category: 'Organize',
    icon: 'Wrench',
    accent: 'lavender',
    detail:
      'Rebuild a PDF that the browser can open using the PDF engine’s writer. Severely damaged or incomplete files may not be recoverable.',
    action: 'Rebuild PDF',
  },
];
export const categories: Category[] = ['All tools', 'Edit & sign', 'Organize', 'Convert', 'Secure'];
export const getTool = (id: string): Tool | undefined => tools.find((t) => t.id === id);
export const popularIds: ToolId[] = [
  'edit',
  'scan',
  'merge',
  'split',
  'compress',
  'sign',
  'images-to-pdf',
];
